app_nginx_conf_src: "nginx.conf.j2"
app_nginx_conf_dest: "/etc/nginx/default.d/vagrant.conf"
app_svr_dir: "/vagrant/server"
app_web_dir: "/vagrant/web"
app_web_dist_dir: "{{ app_web_dir }}/dist/rouge-like-mmo-web"
app_log_dir: "/var/log/local/rouge-like-mmo"
app_db:
  - rougelikemmo_master_db
  - rougelikemmo_global_db
  - rougelikemmo_shardable_db1
  - rougelikemmo_shardable_db2
  - rougelikemmo_admin_db
app_db_users:
  - user: rougelikemmo_usr
    password: "rougeL!kemmo01"
    privilege: "rougelikemmo_master_db.*:ALL/rougelikemmo_global_db.*:ALL/rougelikemmo_shardable_db1.*:ALL/rougelikemmo_shardable_db2.*:ALL/rougelikemmo_admin_db.*:ALL" # FIXME: この書き方だと二度目以降のansibleでエラーになる模様
