app_nginx_conf_src: "nginx.conf.j2"
app_nginx_conf_dest: "/etc/nginx/default.d/vagrant.conf"
app_svr_dir: "/vagrant/server"
app_web_dir: "/vagrant/client"
app_web_dist_dir: "{{ app_web_dir }}/dist/nothingness-web"
app_log_dir: "/var/log/local/nothingness-app"
app_db:
  - nothingness_master_db
  - nothingness_global_db
  - nothingness_admin_db
app_db_users:
  - user: nothingness_usr
    password: "nothingness01"
    privilege: "nothingness_master_db.*:ALL/nothingness_global_db.*:ALL/nothingness_admin_db.*:ALL" # FIXME: この書き方だと二度目以降のansibleでエラーになる模様
